package com.kal;

import java.util.Scanner;
public class Main {
    static Scanner scanner = new Scanner(System.in);
    static int shapeChoice;
    static int[] x = new int[2];
    static int[] y = new int[2];
    static float[] r = new float[2];
    static float[] h = new float[2];
    public static void main(String[] args) {
        System.out.println("This program generates a shape based on random values");
        System.out.println("\nChoose a shape\n1. Rectangle\n2. Circle\n3. Cylinder");
        inputShape();
        switchShape();
    }

    public static void inputShape(){
        shapeChoice = scanner.nextInt();
        if (shapeChoice < 0 || shapeChoice> 3) {
            System.out.println("re-enter a valid value.");
            inputShape();
        }
    }
    public static boolean equals(){
        if(x[0]==x[1]){
            if(y[0]==y[1]){
                if(r[0] == r[1]){
                    return h[0] == h[1];
                }
            }
        }
        return false;
    }
    public static void switchShape(){
        switch (shapeChoice) {
            case 1 -> {
                System.out.println("The rectangle is generated by having four random numbers as the points of its corner");
                Rectangle[] rects = new Rectangle[1];
                // Initialize the rectangles as arbitrary sizes and at arbitrary positions:
                rects[0] = new Rectangle(Math.random() * 100, Math.random() * 100, Math.random() * 100, Math.random() * 100);
                System.out.println(rects[0]);
            }
            case 2 -> {
                Circle[] circs = new Circle[2];
                System.out.println("The circle is generated by having three random numbers as the points of its center and radius");
                for (int i = 0; i < circs.length; ++i) {
                    x[i] = (int) (Math.random() * 100);
                    y[i] = (int) (Math.random() * 100);
                    r[i] = (float) ((Math.round((Math.random() * 100)*100.0))/100.0);
                    h[i] = 0;//needed the height value to be equal since the equals is used both for cylinder and circle
                    circs[i] = new Circle(x[i], y[i], r[i]);
                    System.out.println("\nCircle " + (i + 1) + "\n" + circs[i]);
                }
                System.out.println("\ncircle 1 & circle 2 equal: " + equals());
            }
            case 3 -> {
                System.out.println("The cylinder is generated by having four random numbers as the points of its center and radius of the circle, and height");
                Cylinder[] cylins = new Cylinder[2];
                Circle[] circs = new Circle[2];
                for (int i = 0; i < cylins.length; ++i) {
                    x[i] = (int) (Math.random() * 100);
                    y[i] = (int) (Math.random() * 100);
                    r[i] = (float) ((Math.round((Math.random() * 100)*100.0))/100.0);
                    h[i] = (float) ((Math.round((Math.random() * 100)*100.0))/100.0);
                    cylins[i] = new Cylinder(x[i], y[i], r[i], h[i]);
                    circs[i] = new Circle(x[i], y[i], r[i]);
                    System.out.println("\nCylinder " + (i + 1) + "\n" + cylins[i]);
                }
                System.out.println("\ncylinder 1 & cylinder 2 equal: " + equals());
            }
        }
    }
}

